father('Andrey_Zemskiy','Elena_Zemskaya').
father('Andrey_Zemskiy','Olga_Zemskaya').
father('Athanasiy_Bulgakov','Elena_Bulgakova').
father('Athanasiy_Bulgakov','Ivan_Bulgakov').
father('Athanasiy_Bulgakov','Mikhail_Bulgakov').
father('Athanasiy_Bulgakov','Nadegda_Bulgakova').
father('Athanasiy_Bulgakov','Nikolay_Bulgakov').
father('Athanasiy_Bulgakov','Varvara_Bulgakova').
father('Athanasiy_Bulgakov','Vera_Bulgakova').
father('Ivan_Bulgakov','Athanasiy_Bulgakov').
father('Ivan_Bulgakov','Irina_Bulgakova').
father('Leonid_Karum','Irina_Karun').
father('Mark_Grinberg','Grinberg_Mikhail').
father('Mikhail_Pokrovskiy','Varvara_Pokrovskaya').
father('Mikhail_Svatlaev','Varvara_Svatlaeva').
father('Nikolay_Davidov','Nikolay_Davidov_2').
father('Sergey_Karum','Leonid_Karum').
father('Sergey_Nurnberg','Elena_Nurnberg').
father('Vsevolod_Evdokimov','Ludmila_Evdokimova').
mother('Aleksandra_Gorskaya','Elena_Nurnberg').
mother('Anfisa_Turbina','Varvara_Pokrovskaya').
mother('Elena_Bulgakova','Varvara_Svatlaeva').
mother('Elena_Zemskaya','Ludmila_Evdokimova').
mother('Ludmila_Evdokimova','Grinberg_Mikhail').
mother('Maria_Miotiskaya','Leonid_Karum').
mother('Nadegda_Bulgakova','Elena_Zemskaya').
mother('Nadegda_Bulgakova','Olga_Zemskaya').
mother('Natalya_Minko','Irina_Bulgakova').
mother('Olimpiada_Ivanova','Athanasiy_Bulgakov').
mother('Sofya_Bestugova','Nikolay_Davidov_2').
mother('Varvara_Bulgakova','Irina_Karun').
mother('Varvara_Pokrovskaya','Elena_Bulgakova').
mother('Varvara_Pokrovskaya','Ivan_Bulgakov').
mother('Varvara_Pokrovskaya','Mikhail_Bulgakov').
mother('Varvara_Pokrovskaya','Nadegda_Bulgakova').
mother('Varvara_Pokrovskaya','Nikolay_Bulgakov').
mother('Varvara_Pokrovskaya','Varvara_Bulgakova').
mother('Varvara_Pokrovskaya','Vera_Bulgakova').
