father('Andrey_Zemskiy','Elena_Zemskaya').
father('Andrey_Zemskiy','Olga_Zemskaya').
father('Athanasiy_Bulgakov','Elena_Bulgakova').
father('Athanasiy_Bulgakov','Ivan_Bulgakov_2').
father('Athanasiy_Bulgakov','Mikhail_Bulgakov').
father('Athanasiy_Bulgakov','Nadegda_Bulgakova').
father('Athanasiy_Bulgakov','Nikolay_Bulgakov').
father('Athanasiy_Bulgakov','Varvara_Bulgakova').
father('Athanasiy_Bulgakov','Vera_Bulgakova').
father('Ivan_Bulgakov','Athanasiy_Bulgakov').
father('Ivan_Bulgakov_2','Irina_Bulgakova').
father('Leonid_Karum','Irina_Karun').
father('Mark_Grinberg','Grinberg_Mikhail').
father('Mikhail_Pokrovskiy','Varvara_Pokrovskaya').
father('Mikhail_Svatlaev','Varvara_Svatlaeva').
father('Nikolay_Davidov','Nikolay_Davidov_2').
father('Sergey_Karum','Leonid_Karum').
father('Sergey_Nurnberg','Elena_Nurnberg').
father('Vsevolod_Evdokimov','Ludmila_Evdokimova').
mother('Aleksandra_Gorskaya','Elena_Nurnberg').
mother('Anfisa_Turbina','Varvara_Pokrovskaya').
mother('Elena_Bulgakova','Varvara_Svatlaeva').
mother('Elena_Zemskaya','Ludmila_Evdokimova').
mother('Ludmila_Evdokimova','Grinberg_Mikhail').
mother('Maria_Miotiskaya','Leonid_Karum').
mother('Nadegda_Bulgakova','Elena_Zemskaya').
mother('Nadegda_Bulgakova','Olga_Zemskaya').
mother('Natalya_Minko','Irina_Bulgakova').
mother('Olimpiada_Ivanova','Athanasiy_Bulgakov').
mother('Sofya_Bestugova','Nikolay_Davidov_2').
mother('Varvara_Bulgakova','Irina_Karun').
mother('Varvara_Pokrovskaya','Elena_Bulgakova').
mother('Varvara_Pokrovskaya','Ivan_Bulgakov_2').
mother('Varvara_Pokrovskaya','Mikhail_Bulgakov').
mother('Varvara_Pokrovskaya','Nadegda_Bulgakova').
mother('Varvara_Pokrovskaya','Nikolay_Bulgakov').
mother('Varvara_Pokrovskaya','Varvara_Bulgakova').
mother('Varvara_Pokrovskaya','Vera_Bulgakova').
pol('Aleksandra_Gorskaya','F').
pol('Andrey_Zemskiy','M').
pol('Anfisa_Turbina','F').
pol('Athanasiy_Bulgakov','M').
pol('Boris_Matveev','M').
pol('Elena_Bulgakova','F').
pol('Elena_Nurnberg','F').
pol('Elena_Zemskaya','F').
pol('Grinberg_Mikhail','M').
pol('Irina_Bulgakova','F').
pol('Irina_Karun','F').
pol('Ivan_Bulgakov','M').
pol('Ivan_Bulgakov_2','M').
pol('Ksenia_Yahontova','F').
pol('Leonid_Karum','M').
pol('Ludmila_Evdokimova','F').
pol('Maria_Miotiskaya','F').
pol('Mark_Grinberg','M').
pol('Mikhail_Bulgakov','M').
pol('Mikhail_Pokrovskiy','M').
pol('Mikhail_Svatlaev','M').
pol('Nadegda_Bulgakova','F').
pol('Natalya_Minko','F').
pol('Nikolay_Bulgakov','M').
pol('Nikolay_Davidov_2','M').
pol('Nikolay_Davidov','M').
pol('Olga_Zemskaya','F').
pol('Olimpiada_Ivanova','F').
pol('Sergey_Karum','M').
pol('Sergey_Nurnberg','M').
pol('Sofya_Bestugova','F').
pol('Varvara_Bulgakova','F').
pol('Varvara_Pokrovskaya','F').
pol('Varvara_Svatlaeva','F').
pol('Vera_Bulgakova','F').
pol('Vsevolod_Evdokimov','M').
